### PR TITLE
Ensure administrative access for developers

### PR DESCRIPTION
**Pull request by whoojemaflip**
Add some documentation about permissions, to help developers avoid being stymied by the **Permission Denied** screen.

### CODE REVIEW

**Comment by tijmenb** [comment]
I'm a bit unsure about this, because it prevents developers from using the app as a real user.

As a low-fi alternative, maybe we can show a specific error message in development that explains how to update the users' permissions? I always use `User.first.update permissions: ["signin", "GDS Editor"]`

**Comment by whoojemaflip** [comment]
@tijmenb How easy is it to edit the **Permission Denied** page from a client app?

**Comment by tijmenb** [comment]
Add this to the controller and/or override the template:

https://github.com/alphagov/gds-sso/blob/master/lib/gds-sso/controller_methods.rb#L8-L10

**Comment by tomsabin** [comment]
I ran into this problem yesterday when I got the application up and running for the first time, thankfully @whoojemaflip pointed me to this PR otherwise I probably would have fell into a rabbit hole. 

If we didn't want to change the application just for the development environment, perhaps we could explain the user permissions and include `User.first.update permissions: ["signin", "GDS Editor"]` in the "Running the application" section of the README?

**Comment by whoojemaflip** [comment]
@tijmenb @tomsabin I've removed the more far-out commits, so this is just a documentation change now.

**Pull request merged**
