### PR TITLE
Remove auto-linting in specs

### PR DESCRIPTION
**Pull request by tijmenb**
I find this behaviour more annoying than having the build occasionally fail on CI.

### CODE REVIEW

**Comment by tijmenb** [comment]
@mobaig / @carvil thoughts?

**Comment by carvil** [comment]
It's fine now as all past issues have been fixed. From now on, we will get a sad face from jenkins on new issues (in the diff), which is fine by me. 👍

**Comment by tijmenb** [comment]
Cool. Can you merge?

**Comment by carvil** [comment]
Yup, was just waiting to see if there were more comments.

**Pull request merged**
